ip: localhost

server:
  port: 8010

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://192.168.10.24/config/config_files.git # 配置git仓库地址
          search-paths: config-* # 配置仓库路径
          username: root # 访问git仓库的用户名
          password: 12345678 # 访问git仓库的用户密码
          force-pull: true # 强制从远程库中更新本地库

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@${ip}:1025/eureka
      service-id: ${spring.application.name}
